### ISSUE TITLE
0.11 no longer compiles

### ISSUE THREAD

**Issue by NikosEfthias** [actix/actix#489]
Your issue may already be reported!
Please search on the [Actix issue tracker](https://github.com/actix/actix/issues) before creating one.

## Expected Behavior

Project to compile

## Current Behavior

Compilation error
## Steps to Reproduce (for bugs)

1.add actix 0.11 to cargo toml
2. run cargo check

* Rust Version (I.e, output of `rustc -V`):rustc 1.51
* Actix Version: 0.11

```
warning: state:::180
warning: api:::185
warning: ws:::189
    Checking actix v0.11.1
warning: unused import: `actix_cors::Cors`
 --> api/src/lib.rs:1:5
  |
1 | use actix_cors::Cors;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

error: unexpected token: `MapProjReplace`
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:13:25
   |
13 |     #[project_replace = MapProjReplace]
   |                         ^^^^^^^^^^^^^^

error: cannot find attribute `project_replace` in this scope
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:13:7
   |
13 |     #[project_replace = MapProjReplace]
   |       ^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared type `MapProjReplace`
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:50:21
   |
50 |                     MapProjReplace::Incomplete { f, .. } => Poll::Ready(f(output, act, ctx)),
   |                     ^^^^^^^^^^^^^^ use of undeclared type `MapProjReplace`

error[E0433]: failed to resolve: use of undeclared type `MapProjReplace`
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:51:21
   |
51 |                     MapProjReplace::Complete => unreachable!(),
   |                     ^^^^^^^^^^^^^^ use of undeclared type `MapProjReplace`

error[E0425]: cannot find value `MapProjReplace` in this scope
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:13:25
   |
13 |     #[project_replace = MapProjReplace]
   |                         ^^^^^^^^^^^^^^ not found in this scope

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:13:25
   |
13 |     #[project_replace = MapProjReplace]
   |                         ^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0599]: no method named `project_replace` found for struct `Pin<&mut fut::future::map::Map<Fut, F>>` in the current scope
  --> /home/nikos/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/fut/future/map.rs:49:28
   |
49 |                 match self.project_replace(Map::Complete) {
   |                            ^^^^^^^^^^^^^^^ method not found in `Pin<&mut fut::future::map::Map<Fut, F>>`

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0425, E0433, E0599, E0658.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `actix`

To learn more, run the command again with --verbose.
```

**Comment by fakeshadow** [comment]
run `cargo update` first when you already have a lock file in folder. Or start a new project to test with a fresh lock file.

**Comment by NikosEfthias** [comment]
@fakeshadow that seems to solve the issue thanks. I thought updating the version in the manifest would update the actual dependency

**Comment by tmpolaczyk** [comment]
@NikosEfthias you are right, you shouldn't have to manually run cargo update. This is because the actix Cargo.toml specifies `pin-project-lite = "0.2"` when that's not true because it doesn't compile with `pin-project-lite = "0.2.0"`. It should be `pin-project-lite = "0.2.6"` instead. Since version 0.2.0 is yanked this does not affect new projects, only projects that did already depend on `pin-project-lite = "0.2.0"` before updating the version of actix. So in my case I was able to solve this by running:

    cargo update -p pin-project-lite:0.2.0

**Comment by fakeshadow** [comment]
`project-lite = "0.2"` actually means `^0.2`. It does not pin to `0.2.0` and actix 0.11 accept any `project-lite` in the range of 0.2 - 0.3

Look at cargo book and SemVer guidelines it linked for understanding the difference here.
https://doc.rust-lang.org/cargo/reference/resolver.html?highlight=version#recommendations

**Comment by tmpolaczyk** [comment]
Yes, the actix Cargo.toml specifies that actix should accept any version that starts with 0.2, such as 0.2.0 or 0.2.6. But it doesn't compile when used with 0.2.0, so it should be changed to `pin-project-lite = "0.2.6"`. That would not require manual intervention by users because cargo will automatically update 0.2.0 to 0.2.6 in that case, without having to run cargo update.

**Comment by fakeshadow** [comment]
No it should not.

https://crates.io/crates/pin-project-lite/versions

You can see 0.2.5 is still there and if you look down there are multiple yanked version. That's why you need update.
It's not actix's job to track every yank situation of deps and we give a working range and that's all.

**Comment by fakeshadow** [comment]
The situation is very simple. If you have a yanked version in your lock you have to run `cargo update`. That has nothing to do with actix.

If you don't have it. You can not make actix import a yanked one.

**Comment by tmpolaczyk** [comment]
Yes, I agree that it's not actix job, it's probably the fault of the pin-project-lite developers for making a breaking change and calling it 0.2.6 instead of 0.3.
