### ISSUE TITLE
`trust-dns-proto` fails to compile

### ISSUE THREAD

**Issue by Turbo87** [actix/actix#177]
After updating actix from v0.7.5 to v0.7.6 I'm seeing the following failures on TravisCI:

```
Downloading trust-dns-resolver v0.10.0
   Compiling trust-dns-proto v0.5.0
error[E0432]: unresolved import `tokio_timer::Timeout`
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.5.0/src/tcp/tcp_stream.rs:20:5
   |
20 | use tokio_timer::Timeout;
   |     ^^^^^^^^^^^^^^^^^^^^ no `Timeout` in the root
error[E0599]: no method named `context` found for type `tokio_executor::SpawnError` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.5.0/src/error.rs:293:11
    |
293 |         e.context(ProtoErrorKind::SpawnError).into()
    |           ^^^^^^^
    |
    = note: the method `context` exists but the following trait bounds were not satisfied:
            `tokio_executor::SpawnError : failure::Fail`
            `&tokio_executor::SpawnError : failure::Fail`
            `&mut tokio_executor::SpawnError : failure::Fail`
error[E0277]: the trait bound `futures::Future<Item=tcp::tcp_stream::TcpStream<tokio_tcp::TcpStream>, Error=std::io::Error> + std::marker::Send: std::marker::Sized` is not satisfied
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.5.0/src/tcp/tcp_stream.rs:145:10
    |
145 |         (Box::new(stream), message_sender)
    |          ^^^^^^^^ `futures::Future<Item=tcp::tcp_stream::TcpStream<tokio_tcp::TcpStream>, Error=std::io::Error> + std::marker::Send` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Item=tcp::tcp_stream::TcpStream<tokio_tcp::TcpStream>, Error=std::io::Error> + std::marker::Send`
    = note: required by `<std::boxed::Box<T>>::new`
```

It seems a little unfortunate that such a problematic dependency was added in just a patch update. Are there any known workarounds for this problem?

**Comment by Turbo87** [comment]
@DoumanAsh I tried to disable the `cargo` cache in https://github.com/Turbo87/ogn-web-gateway/pull/86, but as you can see in https://travis-ci.org/Turbo87/ogn-web-gateway/jobs/459641550 that does not solve the problem.

**Comment by DoumanAsh** [comment]
Yes, because it still uses old verson `Downloading tokio-timer v0.2.4`

**Comment by Turbo87** [comment]
hmm, if actix needs a newer `tokio-timer` then maybe https://github.com/actix/actix/blob/v0.7.6/Cargo.toml#L48 needs to be updated?

**Comment by DoumanAsh** [comment]
I guess we can, but ur code doesn't depend on it I think

Also do not store lock file in repo, it is bad practice https://github.com/Turbo87/ogn-web-gateway/blob/master/Cargo.lock#L1849-L1856

It pins you to old version of tokio-timer

**Comment by Turbo87** [comment]
> Also do not store lock file in repo, it is bad practice https://github.com/Turbo87/ogn-web-gateway/blob/master/Cargo.lock#L1849-L1856

I very much disagree. For apps (this is not a library) this is officially recommended by the Rust team and what `cargo new` generates by default.

> I guess we can, but our code doesn't depend on it I think

if the code does not depend on it then why is there a dependency on it?

> It pins you to old version of tokio-timer

if any code depends on a newer version of `tokio-timer` then the dependency needs to be updated. if the dependency is updated then the lockfile would also be updated if necessary.

**Comment by DoumanAsh** [comment]
>I very much disagree. For apps (this is not a library) this is officially recommended by the Rust team and what cargo new generates by default.

Argument from authority is no valid.
You use lock files when you want to control update of your dependencies, instead of leaving it to cargo and semver.
If you need it, then please expect to manually run `cargo update` when needed.
Further queries about not updating `tokio-timer` should be directed to `trust-dns` repo, because actix is not responsible for `trust-dns`

>if the code does not depend on it then why is there a dependency on it?

We only use `tokio_timer::clock` which is 0.2.4
We might need to update min version, but we had no issue with our current `^0.2` placement

>if any code depends on a newer version of tokio-timer then the dependency needs to be updated

We do not need to update it anymore because it automatically picks latest

**Comment by Turbo87** [comment]
good news for anyone running into this problem, I've worked around the issue for now. the following commands were necessary to update the relevant dependencies in the lockfile:

```bash
cargo update -p slab:0.4.0 --precise 0.4.1
cargo update -p tokio-timer --precise 0.2.8
cargo update -p tokio-executor --precise 0.1.5
```

(see https://github.com/Turbo87/ogn-web-gateway/pull/86)

> Argument from authority is no valid.
> You use lock files when you want to control update of your dependencies, instead of leaving it to cargo and semver.

I don't think this is correct. https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ is a good blog post that details why lockfiles for apps make sense. It's for Ruby, but from one of the authors of `cargo` so still quite relevant.

**Comment by fafhrd91** [comment]
We will pin new version, but this will need to wait until next release

**Comment by t3hmrman** [comment]
Just want to note that I ran into this today (updating an old project) and `cargo update` worked :)

**Comment by candronikos** [comment]
Getting the same error. `cargo update` didn't work this time.

```
C:\Users\user\project>cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling trust-dns-proto verror0.6.3: cannot find derive macro `Fail` in this scope

  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:33:32
   |
33 | #[derive(Eq, PartialEq, Debug, Fail)]
   |                                ^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:297:11
    |
297 | impl From<tokio_timer::timeout::Error<ProtoError>> for ProtoError {
    |           ^^^^^^^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:298:16
    |
298 |     fn from(e: tokio_timer::timeout::Error<ProtoError>) -> Self {
    |                ^^^^^^^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\udp\udp_client_stream.rs:95:20
   |
95 |     let mut rand = rand::thread_rng();
   |                    ^^^^

error[E0658]: The attribute `fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:36:5
   |
36 |     #[fail(display = "future was canceled: {:?}", _0)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:40:5
   |
40 |     #[fail(display = "char data length exceeds {}: {}", _0, _1)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:49:5
   |
49 |     #[fail(display = "overlapping labels name {} other {}", _0, _1)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:58:5
   |
58 |     #[fail(display = "dns key value unknown, must be 3: {}", _0)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> C:\Users\Chris\.cargo\registry\src\github.com-1ecc6299db9ec823\trust-dns-proto-0.6.3\src\error.rs:62:5
   |
62 |     #[fail(display = "name label data exceed 255: {}", _0)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by candronikos** [comment]
To follow up, I got past the issue by compiling without the `"resolver"` feature.

**Comment by DoumanAsh** [comment]
ehm.. weird, I recently built `actix-web` without problem
