### ISSUE TITLE
Can't return Future from fn handle

### ISSUE THREAD

**Issue by mocsy** [actix/actix#312]
This example works with actix 0.8.
It stoped working with 0.9 and I found no mention of this in changes.
Also nothing about this in the docs, or my googling didn't turn up the right doc.
Is this a regression?

```rust
pub struct MyActorAsync {}
impl Actor for MyActorAsync {
    type Context = actix::Context<Self>;
    fn started(&mut self, _ctx: &mut Self::Context) {
        debug!("MyActorAsync alive.");
    }
}

#[derive(Debug)]
pub struct MyError{}
impl std::fmt::Display for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DunnoWhat")
    }
}
impl std::error::Error for MyError{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}
pub struct MyQuestion{}
impl Message for MyQuestion {
    type Result = Result<Vec<String>, MyError>;
}
impl Handler<MyQuestion> for MyActorAsync {
    type Result = Box<dyn Future<Item = Vec<String>, Error = MyError>>;
    fn handle(&mut self, question: MyQuestion, _ctx: &mut Context<Self>) -> Self::Result {
        let fut = futures::future::ok(vec!("".to_owned()));
        Box::new(fut)
    }
}
```

This is the error with 0.9:

```rust
error[E0277]: the trait bound `std::boxed::Box<(dyn futures::future::Future<Error = actor::MyError, Item = std::vec::Vec<std::string::String>> + 'static)>: actix::handler::MessageResponse<actor::MyActorAsync, actor::MyQuestion>` is not satisfied
   --> src/actor.rs:140:5
    |
139 | impl Handler<MyQuestion> for MyActorAsync {
    | ----------------------------------------- in this `impl` item
140 |     type Result = Box<dyn Future<Item = Vec<String>, Error = MyError>>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::handler::MessageResponse<actor::MyActorAsync, actor::MyQuestion>` is not implemented for `std::boxed::Box<(dyn futures::future::Future<Error = actor::MyError, Item = std::vec::Vec<std::string::String>> + 'static)>`
    |
    = help: the following implementations were found:
              <std::boxed::Box<(dyn actix::fut::ActorFuture<Actor = A, Output = std::result::Result<I, E>> + 'static)> as actix::handler::MessageResponse<A, M>>

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `arangoq`.

To learn more, run the command again with --verbose.
```

**Comment by JohnTitor** [comment]
At a glance, you should use actor's future, not std's one, I guess.

```diff
-- type Result = Box<dyn Future<Item = Vec<String>, Error = MyError>>;
++ type Result = ResponseActFuture<Self, Result<Vec<String>, MyError>>;
```

Also, should convert returned future to actor's one by `into_actor()`, it should compile fine.

**Comment by mocsy** [comment]
> At a glance, you should use actor's future, not std's one, I guess.
> 
> ```diff
> -- type Result = Box<dyn Future<Item = Vec<String>, Error = MyError>>;
> ++ type Result = ResponseActFuture<Self, Result<Vec<String>, MyError>>;
> ```
> 
> Also, should convert returned future to actor's one by `into_actor()`, it should compile fine.

That didn't work either.

```rust
pub struct MyActorAsync {}
impl Actor for MyActorAsync {
    type Context = actix::Context<Self>;
    fn started(&mut self, _ctx: &mut Self::Context) {
        debug!("MyActorAsync alive.");
    }
}

#[derive(Debug)]
pub struct MyError{}
impl std::fmt::Display for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DunnoWhat")
    }
}
impl std::error::Error for MyError{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}
pub struct MyQuestion{}
impl Message for MyQuestion {
    type Result = Result<Vec<String>, MyError>;
}
impl Handler<MyQuestion> for MyActorAsync {
    type Result = ResponseActFuture<MyActorAsync, Result<Vec<String>,MyError>>;
    fn handle(&mut self, question: MyQuestion, _ctx: &mut Context<Self>) -> Self::Result {
        let fut = futures::future::ok(vec!("".to_owned()));
        fut.into_actor(self)
    }
}
```

**Comment by mocsy** [comment]
For future googlers. upgrading to futures 0.3 form 0.1 is required to make the above work.

How to make the same work without the Result<I, E> wrap (see bellow)?

```rust
pub struct MyActorAsync {}
impl Actor for MyActorAsync {
    type Context = actix::Context<Self>;
    fn started(&mut self, _ctx: &mut Self::Context) {
        debug!("MyActorAsync alive.");
    }
}

#[derive(Debug)]
pub struct MyError{}
impl std::fmt::Display for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DunnoWhat")
    }
}
impl std::error::Error for MyError{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}
pub struct MyQuestion{}
impl Message for MyQuestion {
    type Result = Vec<String>;
}
impl Handler<MyQuestion> for MyActorAsync {
    type Result = ResponseActFuture<MyActorAsync,Vec<String>>;
    fn handle(&mut self, question: MyQuestion, _ctx: &mut Context<Self>) -> Self::Result {
        let fut = futures::future::ready(vec!("".to_owned()));
        Box::new(fut.into_actor(self))
    }
}
```

**Comment by mocsy** [comment]
To further document what works, this is the same thing with ResponseFuture instead of ResponseActFuture:

```rust
pub struct MyActorAsync {}
impl Actor for MyActorAsync {
    type Context = actix::Context<Self>;
    fn started(&mut self, _ctx: &mut Self::Context) {
        debug!("MyActorAsync alive.");
    }
}

#[derive(Debug)]
pub struct MyError{}
impl std::fmt::Display for MyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DunnoWhat")
    }
}
impl std::error::Error for MyError{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}
pub struct MyQuestion{}
impl Message for MyQuestion {
    type Result = Result<Vec<String>,MyError>;
}
impl Handler<MyQuestion> for MyActorAsync {
    type Result = ResponseFuture<Result<Vec<String>, MyError>>;
    fn handle(&mut self, question: MyQuestion, _ctx: &mut Context<Self>) -> Self::Result {
        let fut : futures::future::Ready<Result<Vec<String>, MyError>> = futures::future::ok(vec!("".to_owned()));
        Box::pin(fut)
    }
}
```

Still, I'd like to know how to make the same work with
```rust
impl Message for MyQuestion {
    type Result = Vec<String>;
}
```
instead of
```rust
impl Message for MyQuestion {
    type Result = Result<Vec<String>,MyError>;
}
```

**Comment by JohnTitor** [comment]
Hm, so, it's a migration pain, not a regression, I guess?

**Comment by mocsy** [comment]
Yes the problem occurred with moving from actix 0.8 to 0.9.

**Comment by mocsy** [comment]
I don't know yet how will I move to async syntax, but I put some thought in it and ultimately something like this could be nice:
```rust
#![feature(type_alias_impl_trait)]
pub struct MyQuestion{}
impl Message for MyQuestion {
    type Result = u8;
}
impl Handler<MyQuestion> for MyActorAsync {
    type Result = impl std::future::Future<Output = u8>;
    fn handle(&mut self, question: MyQuestion, _ctx: &mut Context<Self>) -> Self::Result {
        async {5}
    }
}
```

**Comment by UkonnRa** [comment]
For working around the lack of `async fn handle`, I tried the following code, but still not work:

```rust

    struct MockActor;

    impl Handler<Event> for MockActor {
        type Result = ResponseActFuture<Self, Result<(), DomainError>>;

        fn handle(&mut self, msg: Event, ctx: &mut Self::Context) -> Self::Result {
            let fut = self.handle_event(msg);
            Box::new(fut.into_actor(self))
        }
    }

    impl MockHandler {
        async fn handle_event(&self, msg: UserEvent) -> Result<(), DomainError> {
            println!("{:#?}", msg);
            Ok(())
        }
    }
```

Just get errors about `lifetime conflict`:
```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
  --> absolem\src\user\service.rs:63:28
   |
63 |             let fut = self.handle_event(msg);
   |                            ^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 62:9...
  --> absolem\src\user\service.rs:62:9
   |
62 | /         fn handle(&mut self, msg: Event, ctx: &mut Self::Context) -> Self::Result {
63 | |             let fut = self.handle_event(msg);
64 | |             Box::new(fut.into_actor(self))
65 | |         }
   | |_________^
note: ...so that reference does not outlive borrowed content
  --> absolem\src\user\service.rs:63:23
   |
63 |             let fut = self.handle_event(msg);
   |                       ^^^^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the expression is assignable
  --> absolem\src\user\service.rs:64:13
   |
64 |             Box::new(fut.into_actor(self))
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: expected  `std::boxed::Box<(dyn actix::fut::ActorFuture<Actor = user::service::tests::MockActor, Output = std::result::Result<(), error::DomainError>> + 'static)>`
              found  `std::boxed::Box<dyn actix::fut::ActorFuture<Actor = user::service::tests::MockActor, Output = std::result::Result<(), error::DomainError>>>`
```

Any idea?

**Comment by Jonathas-Conceicao** [comment]
@UkonnRa It's currently not possible just like that. The system may poll on other futures while it awaits for any of them to complete , you can't return a future that holds the actor's self reference. You can, however, use `ResponseActFuture`'s `map` and `then` combinators to access and update Actor's internal state. That is some related discussion on #308.

**Comment by UkonnRa** [comment]
@Jonathas-Conceicao Thanks for your quick answer. `clone` works, but I don't want to do `clone`ing in my project, since some of my actors are heavy and may consume a lot if cloning...
