### ISSUE TITLE
actix-web-actors websocket example programs don't compile in actix 0.11.0

### ISSUE THREAD

**Issue by jacobhenn** [actix/actix#485]
## Expected Behavior
Minor release `actix 0.10.0 -> 0.11.0` shouldn't introduce any breaking changes

## Current Behavior
Compiling the example programs [here](https://github.com/actix/examples/blob/master/websockets/websocket/src/main.rs) or [here](https://actix.rs/docs/websockets) with actix 0.11.0, which should be compatable with actix-web-actors (which requires actix ^0.10.0) gives multiple errors almost exactly like this one:
```rust
error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
   --> src/main.rs:9:5
    |
9   |     type Context = ws::WebsocketContext<Self>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
    | 
   ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-3.0.0/src/ws.rs:181:8
    |
181 |     A: Actor<Context = WebsocketContext<A>>,
    |        ------------------------------------ required by this bound in `WebsocketContext`
```

## Steps to Reproduce
1. Create new project; in `main.rs` put the example code found [here](https://actix.rs/docs/websockets)
2. In `Cargo.toml`, put in the latest versions of everything required (specificaly, `actix = "0.11.0"`)
3. `cargo build` and find errors
4. change the version of actix to 0.10.0
5. `cargo build` and find no errors

* Rust Version: 1.49.0

**Comment by robjtede** [comment]
Unstable versions 0.xx are semver exempt in rust, though compatibility is generally expected for patch versions. Use 0.10.

**Comment by lamafab** [comment]
> Unstable versions 0.xx are semver exempt in rust, though compatibility is generally expected for patch versions. Use 0.10 for now.

What do you recommend as a work-around if I need tokio 1.x support?
