### ISSUE TITLE
Breaking change in `actix_derive@0.6.1`

### ISSUE THREAD

**Issue by avandesa-fw** [actix/actix#596]
## Expected Behavior

Code should not fail to compile after a patch version update.

## Current Behavior

Compilation failures appear after updating `actix_derive` from 0.6.0 to 0.6.1.

[`actix_derive@0.6.1`](https://github.com/actix/actix/releases/tag/actix_derive-v0.6.1) internally updated the `syn` dependency to 2.0. After that change, the `#[rtype("()")]` attribute results in a compilation error.

## Possible Solution

* Update how `message::get_attribute_type_multiple` calls `syn::Attr::parse_args` so that the correct  message and span are included in the error. I may be able to open a PR for this.
* Yank `actix_derive@0.6.1` and re-release as `0.7`. A new minor version of `actix` may also need to be released, as it re-exports the macros from `actix_derive`. (I totally understand if this is too much of a hassle, especially a year after the change was first released, but I do want to report this issue in case others run into it as well)

## Steps to Reproduce (for bugs)

With `actix@0.13` and `actix_derive@0.6.0`, the below snippet compiles correctly. With `actix_derive@0.6.1`, it fails:

```rust
use actix_derive::Message;

#[derive(Message)]
#[rtype("()")]
pub struct Message;
```

```
error: Expect an attribute `rtype`
 --> src/lib.rs:5:10
  |
5 | #[derive(Message)]
  |          ^^^^^^^
  |
  = note: this error originates in the derive macro `Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `actix-derive-breaking-change` (lib) due to 1 previous error
```

The error can be resolved by changing the rtype attribute to `#[rtype(result = "()")]`.

## Context

After running `cargo update`, which should only update to compatible versions, we started getting a ton of compilation errors, as we had liberally used `#[rtype("()")]` for our messages.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): `rustc 1.79.0 (129f3b996 2024-06-10)`
- Actix Version: `actix_derive@0.6.1`

**Comment by robjtede** [comment]
fixed in 8c36d6bfc5e71d2b9e66a851477e458071afd9f2 and released as v0.6.2
